CREATE TABLE IF NOT EXISTS urls
(
	id BIGSERIAL PRIMARY KEY,
	short_code TEXT UNIQUE NOT NULL,
	long_url TEXT NOT NULL,
	clicks BIGINT DEFAULT 0,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_short_code ON urls(short_code);
